version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "{{ cookiecutter.python_version }}"
  jobs:
    pre_create_environment:
      # Install poetry
      - pip install poetry
    post_create_environment:
      # Configure poetry
      - poetry config virtualenvs.create false
    post_install:
      # Install only documentation dependencies
      - poetry install --only docs
      # Install the package in development mode, skipping dependencies
      - pip install --no-deps -e .

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
